
export const AGENTS_TYPE = {
    GET_AGENTS_REQUEST: 'GET_AGENTS_REQUEST',
    GET_AGENTS_RECEIVED: 'GET_AGENTS_RECEIVED',
    GET_AGENTS_FAILED: 'GET_AGENTS_FAILED',
    CREATE_AGENT_REQUEST: 'CREATE_AGENT_REQUEST',
    CREATE_AGENT_RECEIVED: 'CREATE_AGENT_RECEIVED',
    CREATE_AGENT_FAILED: 'CREATE_AGENT_FAILED',
    DELETE_AGENT_REQUEST: 'DELETE_AGENT_REQUEST',
    DELETE_AGENT_RECEIVED: 'DELETE_AGENT_RECEIVED',
    DELETE_AGENT_FAILED: 'DELETE_AGENT_FAILED',
    UPDATE_AGENT_REQUEST: 'UPDATE_AGENT_REQUEST',
    UPDATE_AGENT_RECEIVED: 'UPDATE_AGENT_RECEIVED',
    UPDATE_AGENT_FAILED: 'UPDATE_AGENT_FAILED',
};