
export const APARTMENTS_TYPE = {
    GET_APARTMENTS_REQUEST: 'GET_APARTMENTS_REQUEST',
    GET_APARTMENTS_RECEIVED: 'GET_APARTMENTS_RECEIVED',
    GET_APARTMENTS_FAILED: 'GET_APARTMENTS_FAILED',
    CREATE_APARTMENT_REQUEST: 'CREATE_APARTMENT_REQUEST',
    CREATE_APARTMENT_RECEIVED: 'CREATE_APARTMENT_RECEIVED',
    CREATE_APARTMENT_FAILED: 'CREATE_APARTMENT_FAILED',
    DELETE_APARTMENT_REQUEST: 'DELETE_APARTMENT_REQUEST',
    DELETE_APARTMENT_RECEIVED: 'DELETE_APARTMENT_RECEIVED',
    DELETE_APARTMENT_FAILED: 'DELETE_APARTMENT_FAILED',
    UPDATE_APARTMENT_REQUEST: 'UPDATE_APARTMENT_REQUEST',
    UPDATE_APARTMENT_RECEIVED: 'UPDATE_APARTMENT_RECEIVED',
    UPDATE_APARTMENT_FAILED: 'UPDATE_APARTMENT_FAILED',
};