
export const AUTHORIZATION_TYPE = {
    AUTHORIZATION_REQUEST: 'AUTHORIZATION_REQUEST',
    AUTHORIZATION_RECEIVED: 'AUTHORIZATION_RECEIVED',
    AUTHORIZATION_FAILED: 'AUTHORIZATION_FAILED',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESSFULLY: 'LOGOUT_SUCCESSFULLY',
    LOGOUT_FAILED: 'LOGOUT_FAILED',
};