const COLUMN_TYPE = {
    DEFAULT_APARTMENT_COLUMNS: 'DEFAULT_APARTMENT_COLUMNS',
    DEFAULT_AGENT_COLUMNS: 'DEFAULT_AGENT_COLUMNS',
    DEFAULT_CONTRACT_COLUMNS: 'DEFAULT_CONTRACT_COLUMNS',
    DEFAULT_CONTRACT_WITH_AGENCY_COLUMNS: 'DEFAULT_CONTRACT_WITH_AGENCY_COLUMNS',
    DEFAULT_DATA_COLUMNS: 'DEFAULT_DATA_COLUMNS',
    DEFAULT_RATE_COLUMNS: 'DEFAULT_RATE_COLUMNS',
    DEFAULT_USER_COLUMNS: 'DEFAULT_USER_COLUMNS',
    DEFAULT_PHOTO_COLUMNS: 'DEFAULT_PHOTO_COLUMNS',
    DEFAULT_PHOTO_CATALOG_COLUMNS: 'DEFAULT_PHOTO_CATALOG_COLUMNS',
};

export default COLUMN_TYPE;