
export const CONTRACT_WITH_AGENCY_TYPE = {
    GET_CONTRACT_WITH_AGENCY_REQUEST: 'GET_CONTRACT_WITH_AGENCY_REQUEST',
    GET_CONTRACT_WITH_AGENCY_RECEIVED: 'GET_CONTRACT_WITH_AGENCY_RECEIVED',
    GET_CONTRACT_WITH_AGENCY_FAILED: 'GET_CONTRACT_WITH_AGENCY_FAILED',
    CREATE_CONTRACT_WITH_AGENCY_REQUEST: 'CREATE_CONTRACT_WITH_AGENCY_REQUEST',
    CREATE_CONTRACT_WITH_AGENCY_RECEIVED: 'CREATE_CONTRACT_WITH_AGENCY_RECEIVED',
    CREATE_CONTRACT_WITH_AGENCY_FAILED: 'CREATE_CONTRACT_WITH_AGENCY_FAILED',
    DELETE_CONTRACT_WITH_AGENCY_REQUEST: 'DELETE_CONTRACT_WITH_AGENCY_REQUEST',
    DELETE_CONTRACT_WITH_AGENCY_RECEIVED: 'DELETE_CONTRACT_WITH_AGENCY_RECEIVED',
    DELETE_CONTRACT_WITH_AGENCY_FAILED: 'DELETE_CONTRACT_WITH_AGENCY_FAILED',
    UPDATE_CONTRACT_WITH_AGENCY_REQUEST: 'UPDATE_CONTRACT_WITH_AGENCY_REQUEST',
    UPDATE_CONTRACT_WITH_AGENCY_RECEIVED: 'UPDATE_CONTRACT_WITH_AGENCY_RECEIVED',
    UPDATE_CONTRACT_WITH_AGENCY_FAILED: 'UPDATE_CONTRACT_WITH_AGENCY_FAILED',
};