
export const CONTRACTS_TYPE = {
    GET_CONTRACTS_REQUEST: 'GET_CONTRACTS_REQUEST',
    GET_CONTRACTS_RECEIVED: 'GET_CONTRACTS_RECEIVED',
    GET_CONTRACTS_FAILED: 'GET_CONTRACTS_FAILED',
    CREATE_CONTRACT_REQUEST: 'CREATE_CONTRACT_REQUEST',
    CREATE_CONTRACT_RECEIVED: 'CREATE_CONTRACT_RECEIVED',
    CREATE_CONTRACT_FAILED: 'CREATE_CONTRACT_FAILED',
    DELETE_CONTRACT_REQUEST: 'DELETE_CONTRACT_REQUEST',
    DELETE_CONTRACT_RECEIVED: 'DELETE_CONTRACT_RECEIVED',
    DELETE_CONTRACT_FAILED: 'DELETE_CONTRACT_FAILED',
    UPDATE_CONTRACT_REQUEST: 'UPDATE_CONTRACT_REQUEST',
    UPDATE_CONTRACT_RECEIVED: 'UPDATE_CONTRACT_RECEIVED',
    UPDATE_CONTRACT_FAILED: 'UPDATE_CONTRACT_FAILED',
};