
export const DATA_TYPE = {
    GET_DATA_REQUEST: 'GET_DATA_REQUEST',
    GET_DATA_RECEIVED: 'GET_DATA_RECEIVED',
    GET_DATA_FAILED: 'GET_DATA_FAILED',
    CREATE_DATA_REQUEST: 'CREATE_DATA_REQUEST',
    CREATE_DATA_RECEIVED: 'CREATE_DATA_RECEIVED',
    CREATE_DATA_FAILED: 'CREATE_DATA_FAILED',
    DELETE_DATA_REQUEST: 'DELETE_DATA_REQUEST',
    DELETE_DATA_RECEIVED: 'DELETE_DATA_RECEIVED',
    DELETE_DATA_FAILED: 'DELETE_DATA_FAILED',
    UPDATE_DATA_REQUEST: 'UPDATE_DATA_REQUEST',
    UPDATE_DATA_RECEIVED: 'UPDATE_DATA_RECEIVED',
    UPDATE_DATA_FAILED: 'UPDATE_DATA_FAILED',
};