
export const EMPLOYERS_TYPE = {
    GET_EMPLOYERS_REQUEST: 'GET_EMPLOYERS_REQUEST',
    GET_EMPLOYERS_RECEIVED: 'GET_EMPLOYERS_RECEIVED',
    GET_EMPLOYERS_FAILED: 'GET_EMPLOYERS_FAILED',
    CREATE_EMPLOYER_REQUEST: 'CREATE_EMPLOYER_REQUEST',
    CREATE_EMPLOYER_RECEIVED: 'CREATE_EMPLOYER_RECEIVED',
    CREATE_EMPLOYER_FAILED: 'CREATE_EMPLOYER_FAILED',
    DELETE_EMPLOYER_REQUEST: 'DELETE_EMPLOYER_REQUEST',
    DELETE_EMPLOYER_RECEIVED: 'DELETE_EMPLOYER_RECEIVED',
    DELETE_EMPLOYER_FAILED: 'DELETE_EMPLOYER_FAILED',
    UPDATE_EMPLOYER_REQUEST: 'UPDATE_EMPLOYER_REQUEST',
    UPDATE_EMPLOYER_RECEIVED: 'UPDATE_EMPLOYER_RECEIVED',
    UPDATE_EMPLOYER_FAILED: 'UPDATE_EMPLOYER_FAILED',
};