
export const OWNERS_TYPE = {
    GET_OWNERS_REQUEST: 'GET_OWNERS_REQUEST',
    GET_OWNERS_RECEIVED: 'GET_OWNERS_RECEIVED',
    GET_OWNERS_FAILED: 'GET_OWNERS_FAILED',
    CREATE_OWNER_REQUEST: 'CREATE_OWNER_REQUEST',
    CREATE_OWNER_RECEIVED: 'CREATE_OWNER_RECEIVED',
    CREATE_OWNER_FAILED: 'CREATE_OWNER_FAILED',
    DELETE_OWNER_REQUEST: 'DELETE_OWNER_REQUEST',
    DELETE_OWNER_RECEIVED: 'DELETE_OWNER_RECEIVED',
    DELETE_OWNER_FAILED: 'DELETE_OWNER_FAILED',
    UPDATE_OWNER_REQUEST: 'UPDATE_OWNER_REQUEST',
    UPDATE_OWNER_RECEIVED: 'UPDATE_OWNER_RECEIVED',
    UPDATE_OWNER_FAILED: 'UPDATE_OWNER_FAILED',
};