
export const PHOTO_CATALOGS_TYPE = {
    GET_PHOTO_CATALOGS_REQUEST: 'GET_PHOTO_CATALOGS_REQUEST',
    GET_PHOTO_CATALOGS_RECEIVED: 'GET_PHOTO_CATALOGS_RECEIVED',
    GET_PHOTO_CATALOGS_FAILED: 'GET_PHOTO_CATALOGS_FAILED',
    CREATE_PHOTO_CATALOG_REQUEST: 'CREATE_PHOTO_CATALOG_REQUEST',
    CREATE_PHOTO_CATALOG_RECEIVED: 'CREATE_PHOTO_CATALOG_RECEIVED',
    CREATE_PHOTO_CATALOG_FAILED: 'CREATE_PHOTO_CATALOG_FAILED',
    DELETE_PHOTO_CATALOG_REQUEST: 'DELETE_PHOTO_CATALOG_REQUEST',
    DELETE_PHOTO_CATALOG_RECEIVED: 'DELETE_PHOTO_CATALOG_RECEIVED',
    DELETE_PHOTO_CATALOG_FAILED: 'DELETE_PHOTO_CATALOG_FAILED',
    UPDATE_PHOTO_CATALOG_REQUEST: 'UPDATE_PHOTO_CATALOG_REQUEST',
    UPDATE_PHOTO_CATALOG_RECEIVED: 'UPDATE_PHOTO_CATALOG_RECEIVED',
    UPDATE_PHOTO_CATALOG_FAILED: 'UPDATE_PHOTO_CATALOG_FAILED',
};