
export const PHOTOS_TYPE = {
    GET_PHOTOS_REQUEST: 'GET_PHOTOS_REQUEST',
    GET_PHOTOS_RECEIVED: 'GET_PHOTOS_RECEIVED',
    GET_PHOTOS_FAILED: 'GET_PHOTOS_FAILED',
    CREATE_PHOTO_REQUEST: 'CREATE_PHOTO_REQUEST',
    CREATE_PHOTO_RECEIVED: 'CREATE_PHOTO_RECEIVED',
    CREATE_PHOTO_FAILED: 'CREATE_PHOTO_FAILED',
    DELETE_PHOTO_REQUEST: 'DELETE_PHOTO_REQUEST',
    DELETE_PHOTO_RECEIVED: 'DELETE_PHOTO_RECEIVED',
    DELETE_PHOTO_FAILED: 'DELETE_PHOTO_FAILED',
    UPDATE_PHOTO_REQUEST: 'UPDATE_PHOTO_REQUEST',
    UPDATE_PHOTO_RECEIVED: 'UPDATE_PHOTO_RECEIVED',
    UPDATE_PHOTO_FAILED: 'UPDATE_PHOTO_FAILED',
};