
export const RATES_TYPE = {
    GET_RATES_REQUEST: 'GET_RATES_REQUEST',
    GET_RATES_RECEIVED: 'GET_RATES_RECEIVED',
    GET_RATES_FAILED: 'GET_RATES_FAILED',
    CREATE_RATE_REQUEST: 'CREATE_RATE_REQUEST',
    CREATE_RATE_RECEIVED: 'CREATE_RATE_RECEIVED',
    CREATE_RATE_FAILED: 'CREATE_RATE_FAILED',
    DELETE_RATE_REQUEST: 'DELETE_RATE_REQUEST',
    DELETE_RATE_RECEIVED: 'DELETE_RATE_RECEIVED',
    DELETE_RATE_FAILED: 'DELETE_RATE_FAILED',
    UPDATE_RATE_REQUEST: 'UPDATE_RATE_REQUEST',
    UPDATE_RATE_RECEIVED: 'UPDATE_RATE_RECEIVED',
    UPDATE_RATE_FAILED: 'UPDATE_RATE_FAILED',
};