
export const USERS_TYPE = {
    GET_USERS_REQUEST: 'GET_USERS_REQUEST',
    GET_USERS_RECEIVED: 'GET_USERS_RECEIVED',
    GET_USERS_FAILED: 'GET_USERS_FAILED',
    CREATE_USER_REQUEST: 'CREATE_USER_REQUEST',
    CREATE_USER_RECEIVED: 'CREATE_USER_RECEIVED',
    CREATE_USER_FAILED: 'CREATE_USER_FAILED',
    DELETE_USER_REQUEST: 'DELETE_USER_REQUEST',
    DELETE_USER_RECEIVED: 'DELETE_USER_RECEIVED',
    DELETE_USER_FAILED: 'DELETE_USER_FAILED',
    UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
    UPDATE_USER_RECEIVED: 'UPDATE_USER_RECEIVED',
    UPDATE_USER_FAILED: 'UPDATE_USER_FAILED',
};